name: 11ty build
on:
  push:
    branches:
      - master
    paths:
      - src/**

jobs:
  build_11ty:
    name: Build 11ty site
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build 11ty folder
        uses: TartanLlama/actions-eleventy@master
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: dist
          destination_dir: public_html
          publish_branch: gh-pages
          # github_token: ${{ secrets.GITHUB_TOKEN }}
